Use vitest
Jonghakseo/chrome-extension-boilerplate-react-vite pull request #260
Opened 2023-11-06 10:41 UTC by wonkyDD

2023-11-06 11:42 UTC, PatrykKuniczak requested changes

2023-11-06 11:42 UTC, PatrykKuniczak commented on .all-contributorsrc
I think good idea is disable prettier for this file, cause this bot add new contributor to this file automattically and don't reformat like prettier.

2023-11-06 11:42 UTC, PatrykKuniczak commented on README.md
IMO the previouse version is better, cause have short and clear links, paste entire message as a link, isn't good idea.

Create here only the things related to your feature :)

2023-11-06 11:42 UTC, PatrykKuniczak commented on src/pages/devtools/index.html
i think it's bug with prettier, but i think why you run prettier for entire project, i was configure lint-staged, for run prettier and eslint only for staged file.

2023-11-06 11:42 UTC, PatrykKuniczak commented on package.json
> +    "@vitejs/plugin-react": "4.1.1",
You can't update this read more in https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/258#issuecomment-1794608629

2023-11-06 11:42 UTC, PatrykKuniczak commented on package.json
> +    "vite": "4.5.0",
You can't update this read more in https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/258#issuecomment-1794608629

2023-11-06 11:42 UTC, PatrykKuniczak commented on package.json
> +    "vitest": "^0.34.6",
I think the good approach is don't use '^' anyway, but here we have deps bot, and they are looking for new versions, as you can see in other packages we don't have it, but here @Jonghakseo could say more if he want this, let's do it :)

2023-11-06 11:42 UTC, PatrykKuniczak commented on package.json
> +    "jsdom": "^22.1.0",
I think the good approach is don't use '^' anyway, but here we have deps bot, and they are looking for new versions, as you can see in other packages we don't have it, but here @Jonghakseo could say more if he want this, let's do it :)

2023-11-06 12:21 UTC, closed without merging

2023-11-06 15:33 UTC, PatrykKuniczak commented
Don't panic 😁

Let's open new one

2023-11-07 02:16 UTC, wonkyDD commented
@PatrykKuniczak 
I should have rebased the upstream commit beforehand and fixed the current branch, but I got screwed.
Thanks for the feedback.

> You can't update this read more in [#258 (comment)](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/258#issuecomment-1794608629)

To use vitest successfully, we need to upgrade `@vitejs/plugin-react` and `vite`. 
If not, it will encounter this issue https://github.com/vitest-dev/vitest/issues/3283 and tests will continue to fail.

However, after reading the issue you linked to, I realized that I am not able to update it at this time.
I should have read the description of the package update PR beforehand, but I didn't. (apologize for bothering you 🙇)

As you said, I think we should also hold off on [using vitest](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/257) until the issue is resolved or
there is a workaround.

Thanks a lot.

2023-11-07 08:26 UTC, PatrykKuniczak commented
@wonkyDD You no bothered me  😁
If you have small experience with git don't push force, if you no confident your changes, cause you can destroy you work, create also backup branch before rebase, to hqve possibility to recover your work 👻

I was thinking about workaround, i can equal the source of the file, but there's performance on larger files could be sick.

If i have more time on this month, i can try to solve the PR on rollup, then they can relase new version, and then we can pull this and update, as you can see, everything is blocked 😆