inject custom content script from Popup.tsx
Jonghakseo/chrome-extension-boilerplate-react-vite pull request #329
Opened 2023-12-11 11:34 UTC by lealahm

In the above code, I try adding a custom content script folder apart from the default `content` folder, which would be the code that can be injected on the page when the user clicks on a button inside popup.tsx or using background script.

2023-12-11 16:27 UTC, PatrykKuniczak requested changes
I don't think this is good idea to create duplicated content script.

I mean create step by step instruction, where you describe how to use this, dev which want to implement this, can copy content script, describe only how to attach this to project, like you create in this PR, and describe how to use this excecuteScript :)

2023-12-11 16:27 UTC, PatrykKuniczak commented on src/pages/popup/Popup.tsx
> +    console.log(tab.id)
Remove this log

2023-12-11 16:27 UTC, PatrykKuniczak commented on vite.config.ts
> +
Remove this blank spaces

2023-12-29 10:57 UTC, romaindequidt commented on src/pages/popup/Popup.tsx
> +  const injectContentScript = () {
```suggestion
  const injectContentScript = async () => {
```

2023-12-29 11:07 UTC, romaindequidt commented
I try to use your branch and had to following erreur as soon as content script is run at the document start : 
![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/521473/8cedac6b-d573-4cf5-8797-5938119ba7fd)
Have you managed to make it work on your side?

2023-12-29 15:28 UTC, romaindequidt commented
May you relate this pull request to its issue #306 , please ? Thanks,

2023-12-30 04:46 UTC, lealahm commented
@romaindequidt, Hello, I was also facing the same problem once I tested this out and still trying to solve this problem

2024-01-10 10:28 UTC, PatrykKuniczak commented on src/pages/injectedContent/ui/index.tsx
> +root.id = 'chrome-extension-boilerplate-react-vite-content-view-root';
@lealahm Why did you don't commit this suggestion?

2024-01-10 10:30 UTC, PatrykKuniczak commented
@lealahm any moves forward?

2024-01-24 19:51 UTC, tngflx commented
@lealahm @romaindequidt the latest vite preload plugin already solved this problem,  https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/commit/685da06fa0d68d86a0d2eeb4fcf8a5fb3f2fb214

2024-01-28 23:45 UTC, aspiers commented
I don't think these changes are enough; I was doing something very similar but I also needed to change this line:

https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/blob/685da06fa0d68d86a0d2eeb4fcf8a5fb3f2fb214/utils/plugins/inline-vite-preload-script.ts#L10

In the case of this PR, it would need to be:

```ts
 if (!/content|injectedContent/.test(chunk.fileName)) {
```

2024-01-29 00:03 UTC, aspiers commented on src/pages/popup/Popup.tsx
> +    chrome.scripting.executeScript({
This results in

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'executeScript')
```

I think you need to have the `scripting` permission in the manifest.  You also need to have the `activeTab` permission, or have the content script allowed as described here:

https://developer.chrome.com/docs/extensions/reference/api/scripting

2024-01-29 14:40 UTC, enmanuelmag commented
> I try to use your branch and had to following erreur as soon as content script is run at the document start : ![image](https://private-user-images.githubusercontent.com/521473/293351436-8cedac6b-d573-4cf5-8797-5938119ba7fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzkzODEsIm5iZiI6MTcwNjUzOTA4MSwicGF0aCI6Ii81MjE0NzMvMjkzMzUxNDM2LThjZWRhYzZiLWQ1NzMtNGNmNS04Nzk3LTU5MzgxMTliYTdmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxNDM4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTYwYjlmYTJiN2FiOTgzMzA4ZDAzN2VkMTUyOWM1M2Y2MDliMWEwYWExZWY1NWM3YmM5NDEzYmFjMGYwZjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MzxHmx1iaRJjlu7Ohg941Fy0l27JvSSPfc2cl_OfY-w) Have you managed to make it work on your side?

I facing the same problem, is in this [issue](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/376), this PR will solve the problem? I want to preserve the behaviour of inject content automatically without open Popup manually. All code works fine when build in devleopment mode, but in production mode I got the mentioned error.

2024-01-29 23:16 UTC, aspiers commented
> @lealahm @romaindequidt the latest vite preload plugin already solved this problem, [685da06](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/commit/685da06fa0d68d86a0d2eeb4fcf8a5fb3f2fb214)

@tngflx It didn't solve it for me; please can you share a working example?

2024-01-30 02:05 UTC, tngflx commented
@aspiers Hi man, can I know what's your error? By running the inline script by default in vite.config.ts that should do it, that plugin  is just a hook event inside vite upon bundling.

2024-01-30 11:27 UTC, aspiers commented
> Edit : ok I take back my word, the inline script on latest commit is rather buggy, the first line
> 
> ```ts
> if (!/content/.test(chunk.fileName)) {
>               return null;
>      }
> ```
> 
> already f us over...

I already provided this solution in [this comment](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/329#issuecomment-1913763311).

2024-01-30 13:05 UTC, tngflx commented
try my solution 
```ts
async writeBundle(outputOptions, bundle) {
    const outputDir = outputOptions.dir || (outputOptions.file && path.dirname(outputOptions.file));
    let fileToDelete: string | null = null;

    if (!outputDir) {
        console.error('Unable to determine the output directory.');
        return;
    }

    for (const [fileName, outputChunk ] of Object.entries(bundle) as [string, OutputChunk][]) {
        if (!filter(fileName)) {
            continue; // Skip files that don't match the filter
        }

        let modifiedCode = outputChunk.code;

        // Check if the filename contains "index.js"
        if (fileName.includes('index.js')) {
            // Replace import statements with the actual code
            const importStatementRegex = /import\s*\{[^\}]*__vitePreload[^\}]*\}\s*from\s*['"]([^'"]+)['"];/g;
            const exportStatementRegex = /export\s*\{\s*__vitePreload\s*as\s*_\s*\};/g;

            modifiedCode = modifiedCode.replace(importStatementRegex, (_, relativePath) => {
                const absolutePath = path.resolve(outputDir, path.dirname(fileName), relativePath);

                try {
                    let fileContent = fs.readFileSync(absolutePath, 'utf-8');
                    fileContent = fileContent.replace(exportStatementRegex, '');
                    return fileContent;

                } catch (error) {
                    console.error(`Error reading file: ${absolutePath}`, error);
                    return _; // Return the original import statement if there is an error
                }finally {
                    // Store the file path for deletion outside the loop
                    fileToDelete = absolutePath;
                }
            })
        }
        
        try {
            fs.writeFileSync(path.resolve(outputDir, fileName), modifiedCode, 'utf-8');
        } catch (error) {
            console.error(`Error writing file: ${path.resolve(outputDir, fileName)}`, error);
        }

    }

    if (fileToDelete) {
        try {
            fs.unlinkSync(fileToDelete);
        } catch (error) {
            console.error(`Error removing file: ${fileToDelete}`, error);
        }
    }
},
```
I made this solution before i found the latest commit solution, mine works a bit better and skipped the filename check and only focus on index.js

2024-02-18 05:26 UTC, Jonghakseo commented
To be honest, I simply started this boilerplate without full knowledge of Vite and the bundling process of Rollup that it uses internally, and I think this is the time to confront that limitation to some extent.

I'm using a lot of vitePlugins to get things to do what I want, or to fix bugs, and I'm increasingly convinced that a fundamental solution is needed.

And that is to completely tear down this boilerplate and fix it at a lower layer based on rollup.

In the process, I think we can also implement a true HMR (not the inconvenient way we have now, where we throw in a refresh method and a path).

The only limitation is my physical time...

2024-02-18 11:25 UTC, aspiers commented
@Jonghakseo Makes sense, and I totally understand about the lack of time! So grateful for what you already built here so far though; it enabled me to build my extension which probably would have taken too long for me to do by myself!

2024-05-13 16:04 UTC, PatrykKuniczak commented
@Jonghakseo Are you want to implement this PR?

2024-05-16 09:49 UTC, PatrykKuniczak commented
@Jonghakseo One more ping :)

2024-05-20 04:53 UTC, Jonghakseo commented
> @Jonghakseo One more ping :)

Thanks~! I'll check it soon ^^

2024-05-20 18:52 UTC, PatrykKuniczak commented
> > @Jonghakseo One more ping :)
> 
> Thanks~! I'll check it soon ^^

If you decide to move forward with that, maybe i can help with that, it have some months, i need to read it 1 more time :)

2024-06-16 07:06 UTC, PatrykKuniczak commented
@Jonghakseo Let's do something with this thread cause maybe somebody waiting for this feature :)

2024-06-16 13:51 UTC, aspiers commented
I need this feature :stuck_out_tongue_winking_eye: Would be fantastic if a solution was found :pray:

2024-06-16 13:57 UTC, Jonghakseo commented
@PatrykKuniczak @aspiers 

If I understand correctly, this should be worked on top of the legacy branch, is that correct?

2024-06-16 14:15 UTC, Jonghakseo commented
Maybe.... this is solution...? 

- #494

2024-06-16 14:36 UTC, PatrykKuniczak commented
> Maybe.... this is solution...?
> 
> * [Fix PR #329 #494](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/494)

I think so

2024-07-06 07:35 UTC, Jonghakseo commented
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/494

2024-07-06 07:35 UTC, closed without merging