feat: support zip command  #571
Jonghakseo/chrome-extension-boilerplate-react-vite pull request #580
Opened 2024-07-15 10:16 UTC by Leizhenpeng

2024-07-15 10:33 UTC, PatrykKuniczak commented on packages/zipper/index.ts
> +// 打包根目录dist文件
Create description only in english, for better understanding by everybody :)

2024-07-15 10:52 UTC, PatrykKuniczak commented on packages/zipper/lib/zip-bundle/index.ts
> +      if (aborted) return;
it's not better to create
```suggestion
      if (!aborted) {rest code ...}
```

Also below you have the same case

2024-07-15 10:54 UTC, PatrykKuniczak commented on packages/zipper/lib/zip-bundle/index.ts
> +          logPackageSize(size, timer);
Why you don't use data.length directly, this var 'size' seems have no sense, or i don't saw it 😆

2024-07-15 10:56 UTC, PatrykKuniczak commented on packages/zipper/tsconfig.json
> +    "types": ["chrome","node"]
```suggestion
    "types": ["chrome", "node"]
```

2024-07-18 12:11 UTC, Jonghakseo requested changes
<img width="403" alt="스크린샷 2024-07-18 오후 9 09 31" src="https://github.com/user-attachments/assets/33f032b1-60bb-4b47-99a0-9147edc723f5">

It makes a zip file with the entire nested folder structure. 🤔

2024-07-20 12:34 UTC, Leizhenpeng commented
https://github.com/user-attachments/assets/aea84e72-9f49-4028-bcbd-550e5408a60d

@Jonghakseo I haven't reproduced the bug you said.

2024-07-20 12:46 UTC, Leizhenpeng commented
@Jonghakseo It was my negligence. Ha ha, it has been corrected now.

2024-07-20 12:46 UTC, Leizhenpeng commented
![CleanShot 2024-07-20 at 20 46 33@2x](https://github.com/user-attachments/assets/5a1e6141-d2fb-4628-96cb-126928d56643)

2024-07-20 14:13 UTC, Jonghakseo approved these changes
LGTM

2024-07-20 14:59 UTC, PatrykKuniczak commented on packages/zipper/lib/zip-bundle/index.ts
> +      if (aborted) return;
@Leizhenpeng Are you eager and able to implement this?

2024-07-20 15:07 UTC, merged