[Enhance] Add messaging example
Jonghakseo/chrome-extension-boilerplate-react-vite pull request #667
Opened 2024-08-18 17:32 UTC by Jonghakseo

> `*` Please fill in the required items.

## Priority*

- [ ] High: This PR needs to be merged first for other tasks.
- [x] Middle: This PR should be merged quickly to prevent conflicts due to common changes. (default)
- [ ] Low: This PR does not affect other tasks, so it can be merged later.

## Purpose of the PR*

## Changes*

## How to check the feature

## Reference

2024-09-06 13:42 UTC, Jonghakseo commented
# README.md preview

---
# Messaging Package

This package contains code messaging api. 
To use the code in the package, you need to add the following to the package.json file.

```json
{
  "dependencies": {
    "@extension/messaging": "workspace:*"
  }
}
```

## Messaging API

You can use messaging api to send/receive messages between context.

### Usage

```typescript
import { messaging } from '@extension/messaging';

// Send message
messaging.send('message', { data: 'data' });

// Receive message
messaging.on('message', (payload) => {
  console.log(payload.data); // 'data'
  return 'response';
});
```

### Message Types

You should define message types in the `type.ts` file.

```typescript
export interface PayloadAndResponse<P = unknown, D = unknown> {
  payload: P;
  response: D;
}
/**
 * Define the type of messages
 * If you want to add a new message type, you can add it here.
 */
export interface Messages {
  greeting: PayloadAndResponse<string, string>;
  //...
}
```

Then you can take advantage of the message types in the `messaging` api.

```typescript
import { messaging } from '@extension/messaging';


messaging.send('greeting', "Hello").then((response) => {
  console.log(response); // Hi
});
```


```typescript
import { messaging } from '@extension/messaging';

messaging.on('greeting', (payload) => {
  console.log(payload); // Hello
  return 'Hi'; // response
});
```

### SendToCurrentTab

You can use `sendToCurrentTab` to send a message to the current tab.

```typescript
import { messaging } from '@extension/messaging';

messaging.sendToCurrentTab('message', "this is current tab!");
```

You can receive the message in the current tabs `content script`. (e.g. `content` or `content-ui`) 

```typescript
import { messaging } from '@extension/messaging';

messaging.on('message', (payload) => {
  // Do something
});
```

---

2024-09-16 18:12 UTC, PatrykKuniczak requested changes
I think adding this to all pages `package.json` isn't necessary, because users may never used this, and it's additional deps to install.

Rather place it inside `README`

And one more thing refactor from `ready` to `prepare` should be in another PR, but it'll be dumb to move it now, let's leave it there xD

Rest on Discord

2024-09-16 18:12 UTC, PatrykKuniczak commented on packages/messaging/messaging.ts
> +      const response = message.response as Response<T>;
```suggestion
    port.onMessage.addListener(({ type, response }: Message<T>) => {
```
And type for response should be taken from Message

2024-09-16 18:12 UTC, PatrykKuniczak commented on packages/messaging/messaging.ts
> +const createPortUtils = (sendMessage: (message: unknown) => unknown) => {
message should take generic type

2024-09-16 21:08 UTC, govza commented on chrome-extension/src/background/index.ts
> +  return `background received ${payload} message from ${sender?.url}`;
background received [object Object] message from https://example.com/

2024-09-16 21:17 UTC, govza commented on packages/messaging/type.ts
> +  foo: PayloadAndResponse<{ bar: string }, string>;
Maybe more meaningful naming, it's pretty hard to understand at first with foo: bar, what is the protocol what is request types and return types. Maybe HandshakeProtocol, RequestHandshake, ResponseHandshake etc.?

2024-09-16 21:22 UTC, govza commented on packages/messaging/messaging.ts
> +};
Some documentation / jsdoc when / how to use? From background, from content-script send etc?

2024-09-23 05:16 UTC, govza commented on packages/messaging/type.ts
Shouldn't it go to the packages/shared/utils/shared-types?

2024-10-01 05:42 UTC, closed without merging

2024-10-01 05:42 UTC, Jonghakseo commented
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/747

This might be a better alternative, I'll look into it.